on: [workflow_dispatch, push]
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  run-CI:
    name: run CI
    uses: ./.github/workflows/CI.yaml
  release:
    name: release
    if: ${{ startsWith(github.ref, 'refs/tags/') && contains(join(needs.*.result, ','), 'success') }}
    needs: [run-CI]
    uses: ./.github/workflows/release.yaml
